-- user_achievement에 있는 max_count 컬럼은 achievement 테이블로 이동
-- trade_board 테이블에 trade_type 컬럼 추가
-- alert 테이블에 alert_category_id 컬럼 varchar(50)으로 수정
-- user_restricted 테이블에 comment 컬럼 추가
-- collection 테이블에 is_deleted 컬럼 추가
-- maincategory에 color 컬럼 추가
-- board에 is_popular 컬럼 추가
-- collection_photo에 is_primary 컬럼 추가